Repository thecodingcenter/HacktoberFest2022, pull requests merged in 2022-10, with the labels that each got.

#3 Create turtle_pattern.py
  turtle_pattern.py
Labels: HACKTOBERFEST-ACCEPTED

#5 Create thanks.py
  thanks.py
Labels: HACKTOBERFEST-ACCEPTED

#8 added by siddhi
  c.md
Labels: HACKTOBERFEST-ACCEPTED

#12 Create Palindrome.python
  Palindrome.python
Labels: HACKTOBERFEST-ACCEPTED

#11 Create ArmstrongNumber.python
  ArmstrongNumber.python
Labels: HACKTOBERFEST-ACCEPTED

#10 Create LeapYear.python
  LeapYear.python
Labels: HACKTOBERFEST-ACCEPTED

#9 Create Gingerit python tutorial.md
  Gingerit python tutorial.md
Labels: HACKTOBERFEST-ACCEPTED

#13 Create FactorialofaNumber.python
  FactorialofaNumber.python
Labels: HACKTOBERFEST-ACCEPTED

#17 Create code.md
  code.md
Labels: hacktoberfest-accepted

#15 bmiindex.py
  BMIindex.py
Labels: hacktoberfest-accepted

#16 Create Demands 5G and Wi-Fi.md
  Demands 5G and Wi-Fi.md
Labels: hacktoberfest-accepted

#14 added by rohit
  armstrong number.md
Labels: hacktoberfest-accepted

#19 Create tweepy.md
  tweepy.md
Labels: hacktoberfest-accepted

#18 Some important repo on python
  Github repo.md
Labels: hacktoberfest-accepted

#20 Rock-Paper-Scissor Game is added.
  rockpaperscissor.py
Labels: hacktoberfest-accepted

#21 Create binarysearchtree.py
  binarysearchtree.py
Labels: hacktoberfest-accepted

#22 Sudoku Solver using java
  Sudoku Solver/Sudoku.class
  Sudoku Solver/Sudoku.java
Labels: hacktoberfest-accepted

#24 Create Kruskal.java
  Kruskal.java
Labels: hacktoberfest-accepted

#26 Create fibonacci series
  fibonacci series
Labels: hacktoberfest-accepted

#25 Created Greeting.java
  Greeting.java
Labels: hacktoberfest-accepted

#23 ADD hello world script in GOlang
  hello.go
Labels: hacktoberfest-accepted

#38 Create hamiltonprob.java
  hamiltonprob.java
Labels: hacktoberfest-accepted

#36 Create spriallmatrix.cpp
  spriallmatrix.cpp
Labels: hacktoberfest-accepted

#35 Create Binary Search
  BinarySearch.java
Labels: hacktoberfest-accepted

#34 amazon price scraper
  Password Generator.py
  amazon-price-scraper/main.py
  amazon-price-scraper/requirements.txt
Labels: hacktoberfest-accepted

#33 Create String3_Freq
  String3_Freq
Labels: hacktoberfest-accepted

#32 Create Clockwise_Rotate.java
  Clockwise_Rotate.java
Labels: hacktoberfest-accepted

#31 Create Largest.java
  Largest.java
Labels: hacktoberfest-accepted

#30 Create Reverse.java
  Reverse.java
Labels: hacktoberfest-accepted

#29 Created CountNums.java
  CountNums.java
Labels: hacktoberfest-accepted

#39 adds schedule.py
  schedule.py
Labels: hacktoberfest-accepted

#28 Created CaseCheck.java
  CaseCheck.java
Labels: hacktoberfest-accepted

#27 Hello World!!!
  Hello.class
  Hello.java
Labels: hacktoberfest-accepted

#40 countallpossiblepaths.cpp
  countallpossiblepaths.cpp
Labels: hacktoberfest-accepted

#45 Add code for calculating sum of natural numbers
  sum.cpp
Labels: hacktoberfest-accepted

#43 Create occurances.java
  occurances.java
Labels: hacktoberfest-accepted

#42 replaceleastgreater.java
  replaceleastgreater.java
Labels: hacktoberfest-accepted

#41 minchara.java
  minchara.java
Labels: hacktoberfest-accepted

#48 Hacktoberfest2022
  Palindrome.java
Labels: hacktoberfest-accepted

#49 Hacktoberfest2022
  LCM.py
Labels: hacktoberfest2022

#51 Added codes.
  maths.cpp
Labels: hacktoberfest-accepted

#55 Fibonacci Series using recursion
  fibonaccirecursion.c
Labels: hacktoberfest-accepted

#54 Added C++ program for Longest Palindromic Substring
  Longest_palindromic_substring.cpp
Labels: hacktoberfest-accepted

#53 recursive sum.java
  Recursive_Sum_Num.java
Labels: hacktoberfest-accepted

#58 Create hello.java
  hello.java
Labels: hacktoberfest-accepted

#56 Create HelloWorld.java
  HelloWorld.java
Labels: hacktoberfest-accepted

#61 img-show.cpp
  img_show.cpp
Labels: hacktoberfest-accepted

#60 Create findAllDuplicates.java
  findAllDuplicates.java
Labels: hacktoberfest-accepted

#59 Create HelloWorld.cpp
  HelloWorld.cpp
Labels: hacktoberfest-accepted

#63 Create Dutch_National_flag_algorithm.java
  Dutch_National_flag_algorithm.java
Labels: hacktoberfest-accepted

#64 added hello_world_shubham file
  hello_world_shubham.md
Labels: hacktoberfest-accepted

#66 Create Valid_Palindrome.py
  Valid_Palindrome.py
Labels: hacktoberfest-accepted

#65 add print array java
  printArray.java
Labels: hacktoberfest-accepted

#67 C project
  Hospital management/main.c
  Hospital management/readme.md
Labels: hacktoberfest-accepted

#68 Created MergeSort.java
  MergeSort.java
Labels: hacktoberfest-accepted

#69 WildcardMatching
  WildcardMatching.java
Labels: hacktoberfest-accepted

#70 Add files via upload
  Login Form/Users.dat
  Login Form/login.cpp
  Login Form/login.exe
  Login Form/readme.md
Labels: hacktoberfest-accepted

#71 C project
  StudentAssistant-master/Backmenu.h
  StudentAssistant-master/Calculator.c
  StudentAssistant-master/ClassRoutine.c
  StudentAssistant-master/DCalculator.c
  StudentAssistant-master/DemoWallet.c
  StudentAssistant-master/EasyMatrix.c
  StudentAssistant-master/PeriodicTable.c
  StudentAssistant-master/PersonalDiary.c
  StudentAssistant-master/StudentAssistant.c
  StudentAssistant-master/StudentAssistant.exe
  StudentAssistant-master/StudentAssistant.png
Labels: hacktoberfest-accepted

#73 Create guiCalculator.java
  guiCalculator.java
Labels: hacktoberfest-accepted

#77 Create BinarySearchTree.java
  BinarySearchTree.java
Labels: hacktoberfest-accepted

#75 added program in c
  hellloworld.c
Labels: hacktoberfest-accepted

#74 Create factorialusingrecursion
  factorialusingrecursion
Labels: hacktoberfest-accepted

#86 Create Unique_Paths.cpp
  Unique_Paths.cpp
Labels: hacktoberfest-accepted

#85 calculator action applet in java
  calculator.java
Labels: hacktoberfest-accepted

#83 CPP Program To Check String Palindrome Or Not
  StringPalindromeCheck.cpp
Labels: hacktoberfest-accepted

#82 Snake Water Gun game using javascript
  snakeWaterGunGame.js
Labels: hacktoberfest-accepted

#81 Menu driven program for Set operations
  set_operations.py
Labels: hacktoberfest-accepted

#80 Create Stream.java
  Stream.java
Labels: hacktoberfest-accepted

#79 Add GnomeSort.cpp
  GnomeSort.cpp
Labels: hacktoberfest-accepted

#89 binary search
  binarySearch.cpp
Labels: hacktoberfest-accepted

#88 added password generator
  amazon-price-scraper/randomPassGen.py
Labels: hacktoberfest-accepted

#87 Maintain Employee Salary Records using Classes
  Employee_SalarySlip.py
Labels: hacktoberfest-accepted

#91 Create classmatrix.java
  classmatrix.java
Labels: hacktoberfest-accepted

#90 contributed java code
  BT to BST.java
Labels: hacktoberfest-accepted

#92 Read me
  DISHA
  READ ME
Labels: hacktoberfest-accepted

#94 added quicksort program in java
  QuickSort.java
Labels: hacktoberfest2022

#95 rectanglearea added
  CPP/rectanglearea.cpp
Labels: hacktoberfest-accepted
